"""empty message

Revision ID: 1a247d91c090
Revises: 5eb23ca2a192
Create Date: 2020-03-12 00:06:31.049250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a247d91c090'
down_revision = '5eb23ca2a192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('conformed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'conformed')
    # ### end Alembic commands ###
